services:
  - type: web
    name: eleventh-beast-web
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start -- --hostname 0.0.0.0 --port $PORT
    autoDeploy: true
    plan: starter
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
